# This file was heavily based on the ci-file from SymfonyCasts/verify-email-bundle
#
# See https://github.com/SymfonyCasts/verify-email-bundle
#     https://github.com/SymfonyCasts/verify-email-bundle/blob/main/.github/workflows/ci.yml

name: CI
on:
  push:
    branches: ['main','master']
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.1"

      - name: "Validate composer.json"
        run: "composer validate --strict --no-check-lock"

      - name: "Validate php-files"
        run:  "php -l src && php -l tests"

      - name: "Composer install"
        uses: "ramsey/composer-install@v3"
        with:
          composer-options: "--prefer-stable"
          dependency-versions: 'highest'

      - name: "PHP-CS-Fixer"
        run:  "vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php --dry-run"

      - name: "PHPStan"
        run:  "vendor/bin/phpstan analyze"

  tests:
    name: "Tests ${{ matrix.php-version }} ${{ matrix.dependency-versions }}"
    runs-on: ubuntu-22.04
    needs: lint

    strategy:
      fail-fast: false
      matrix:
        # normal, highest, non-dev installs
        php-version: ['8.1', '8.2', '8.3', '8.4']
        composer-options: ['--prefer-stable']
        dependency-versions: ['highest']
        include:
          # testing lowest PHP version with lowest dependencies
          - php-version: '8.1'
            dependency-versions: 'lowest'
            composer-options: '--prefer-lowest'

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - name: "Composer install"
        uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: "${{ matrix.dependency-versions }}"
          composer-options: "--prefer-dist --no-progress"

      - name: Unit Tests
        run: vendor/bin/phpunit